services:
  bds-fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: "http://localhost:5000/api"  # Pass build argument
    ports:
      - "3000:3000"  # Expose port 3000 for the frontend
    networks:
      - bds-network
    depends_on:
      - bds-api  # Ensure bds-api starts before frontend

  bds-api:
    build:
      context: ./Bouvet.Developer.Survey.Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Expose port 5000 for the backend
    networks:
      - bds-network

networks:
  bds-network:
    driver: bridge
