services:
  bds-fe:
    container_name: bds-fe
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://bds-api:5001/api
    ports:
      - "3000:3000"  # Expose port 3000 for the frontend
    networks:
      - bds-network
    depends_on:
      - bds-api  # Ensure bds-api starts before frontend

  bds-api:
    container_name: bds-api
    build:
      context: ./Bouvet.Developer.Survey.Backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5001:5001"  # Expose port 5000 for the backend
    networks:
      - bds-network

networks:
  bds-network:
    driver: bridge
