name: Build and deploy frontend to production
on:
  workflow_dispatch: # manual trigger
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Azure login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_TEST }}

      - name: Enable ACR Admin Account
        run: |
          az acr update -n bouvetSurveyContainerRegistryProd --admin-enabled true

      - name: Get ACR name
        id: getacrname
        run: |
          acrName=$(az acr list --resource-group ${{ secrets.AZURE_RG_PROD }} --query "[0].name" -o tsv)
          echo "ACR_NAME=$acrName" >> $GITHUB_ENV

      - name: Get ACR Credentials
        id: getacrcreds
        run: |
          loginServer=$(az acr list --resource-group ${{ secrets.AZURE_RG_PROD }} --query "[0].loginServer" -o tsv)
          loginName=$(az acr credential show -n ${{ env.ACR_NAME }} --resource-group ${{ secrets.AZURE_RG_PROD }} --query username -o tsv)
          password=$(az acr credential show -n ${{ env.ACR_NAME }} --resource-group ${{ secrets.AZURE_RG_PROD }} --query "passwords[0].value" -o tsv)
          echo "LOGIN_SERVER=$loginServer" >> $GITHUB_ENV
          echo "LOGIN_NAME=$loginName" >> $GITHUB_ENV
          echo "PASSWORD=$password" >> $GITHUB_ENV

      - name: Retrieve Custom Domain from backend container app
        id: get_custom_domain
        run: |
          # Fetch the custom domain using Azure CLI
          CUSTOM_DOMAIN=$(az containerapp show --name bds-prod-containerapp-api --resource-group ${{ secrets.AZURE_RG_PROD }} --query "properties.configuration.ingress.customDomains[0].name" -o tsv)
          # Check if custom domain is found
          if [ -z "$CUSTOM_DOMAIN" ]; then
            echo "Custom domain not found. Failing the pipeline."
            exit 1  # Exit with error if no custom domain is found
          fi

          # Set environment variable for the custom domain
          BACKEND_URL="https://${CUSTOM_DOMAIN}/api"
          echo "BACKEND_URL=${BACKEND_URL}" >> $GITHUB_ENV
          echo "Retrieved backend custom domain: $CUSTOM_DOMAIN"

      - name: Setup frontend .env.production
        id: create_frontend_env
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          envkey_NEXTAUTH_URL: https://survey.bouvetapps.io/
          envkey_AZURE_AD_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          envkey_AZURE_AD_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          envkey_AZURE_AD_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
          envkey_AZURE_AD_BACKEND_CLIENT_ID: ${{ secrets.AZURE_AD_BACKEND_CLIENT_ID }}
          directory: frontend/
          file_name: .env.production
      - name: Print env file
        id: print_env_file
        run: |
          echo "Start: Frontend .env.production created"
          cat frontend/.env.production
          echo "End: Frontend .env.production created"

      - name: Build and Push Frontend Image to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.LOGIN_SERVER }}
          username: ${{ env.LOGIN_NAME }}
          password: ${{ env.PASSWORD }}
      - run: |
          docker compose --env-file frontend/.env.production up
          docker build -f frontend/Dockerfile ./frontend -t ${{ env.LOGIN_SERVER }}/frontend-image:${{ github.sha }} --build-arg NEXT_PUBLIC_API_URL=${{env.BACKEND_URL}}
          docker push ${{ env.LOGIN_SERVER }}/frontend-image:${{ github.sha }}
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Update Container App Image
        run: |
          az containerapp update \
            --name bds-prod-containerapp-frontend \
            --resource-group ${{ secrets.AZURE_RG_PROD }} \
            --image ${{ env.LOGIN_SERVER }}/frontend-image:${{ github.sha }}

      - name: Get Container App URL
        run: |
          fqdn=$(az containerapp show -n bds-prod-containerapp-frontend -g ${{ secrets.AZURE_RG_PROD }} --query properties.configuration.ingress.fqdn -o tsv)
          echo "Container App is deployed at: https://$fqdn"
