name: Build and deploy frontend on PR
on:
  push:
    branches: 
      - '**'
    paths:
      - 'frontend/**'  # Only trigger on changes in frontend directory
      - '.github/workflows/build-and-deploy-frontend-on-pr.yml'
  pull_request:
    branches: 
      - '**'
    paths:
      - 'frontend/**'  # Only trigger on changes in frontend directory
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory: ./frontend  # Set working directory to frontend
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
