name: Build and deploy frontend on Push/PR
on:
  push:
    branches: 
      - '**'
    paths:
      - 'frontend/**'
      - '.github/workflows/build-and-deploy-frontend-on-pr.yml'
  pull_request:
    branches: 
      - '**'
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: 'Azure login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Enable ACR Admin Account
      run: |
        az acr update -n bouvetSurveyContainerRegistryProd --admin-enabled true

    - name: Get ACR name
      id: getacrname
      run: |
        acrName=$(az acr list --resource-group ${{ secrets.AZURE_RG }} --query "[0].name" -o tsv)
        echo "ACR_NAME=$acrName" >> $GITHUB_ENV

    - name: Get ACR Credentials
      id: getacrcreds
      run: |
        loginServer=$(az acr list --resource-group ${{ secrets.AZURE_RG }} --query "[0].loginServer" -o tsv)
        loginName=$(az acr credential show -n ${{ env.ACR_NAME }} --resource-group ${{ secrets.AZURE_RG }} --query username -o tsv)
        password=$(az acr credential show -n ${{ env.ACR_NAME }} --resource-group ${{ secrets.AZURE_RG }} --query "passwords[0].value" -o tsv)
        echo "LOGIN_SERVER=$loginServer" >> $GITHUB_ENV
        echo "LOGIN_NAME=$loginName" >> $GITHUB_ENV
        echo "PASSWORD=$password" >> $GITHUB_ENV
        
    - name: Build and push the Docker image
      working-directory: ./frontend
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.ACR_SERVER }}/bds-frontend-image:${{ github.sha }}
        docker push ${{ secrets.ACR_SERVER }}/bds-frontend-image:${{ github.sha }}