on: 
  push:
    branches:
      - main
    paths:
      - 'infra/**'
name: Deploy to Azure resource group
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy storage account
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: infra/main.bicep
        # parameters: 'storagePrefix=mystore storageSKU=Standard_LRS'
        parameters: infra/main.parameters.json
        failOnStdErr: false